server:
  port: 9003

spring:
  application:
    name: index12306-order${unique-name:}-service
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      password: nacos
      username: nacos
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mapper-locations: classpath:mapper/*.xml

framework:
  fastjson:
    safa-mode: true
  cache:
    redis:
      value-timeout: 16
      value-time-unit: days
