
dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/12306?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

rules:
  - !SHARDING
    tables:
      t_user:
        actualDataNodes: ds_0.t_user_${0..15}
        tableStrategy:
          standard:
            shardingColumn: username
            shardingAlgorithmName: user_hash_mod
      t_order:
        actualDataNodes: ds_0.t_order_${0..15}
        tableStrategy:
          complex:
            shardingColumns: user_id,order_sn
            shardingAlgorithmName: order_table_complex_mod
      t_order_item:
        actualDataNodes: ds_0.t_order_item_${0..15}
        tableStrategy:
          complex:
            shardingColumns: user_id,order_sn
            shardingAlgorithmName: order_item_table_complex_mod
      t_pay:
        actualDataNodes: ds_0.t_pay_${0..15}
        tableStrategy:
          complex:
            shardingColumns: order_sn,pay_sn
            shardingAlgorithmName: pay_table_complex_mod
    shardingAlgorithms:
      user_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16
      order_table_complex_mod:
        type: CLASS_BASED
        props:
          algorithmClassName: org.opengoofy.index12306.biz.orderservice.dao.algorithm.OrderCommonTableComplexAlgorithm
          sharding-count: 16
          strategy: complex
      order_item_table_complex_mod:
        type: CLASS_BASED
        props:
          algorithmClassName: org.opengoofy.index12306.biz.orderservice.dao.algorithm.OrderCommonTableComplexAlgorithm
          sharding-count: 16
          strategy: complex
      pay_table_complex_mod:
        type: CLASS_BASED
        props:
          algorithmClassName: org.opengoofy.index12306.biz.payservice.dao.algorithm.PayTableComplexAlgorithm
          sharding-count: 16
          strategy: complex

props:
  sql-show: false
